-- [E000] Syntax Warning: /Users/ckipp/Documents/scala-workspace/dotty-error-index/./0000_EmptyCatchOrFinallyBlockID.scala:2:2 
2 |  try {}
  |  ^^^^^^
  |  A try without catch or finally is equivalent to putting
  |  its body in a block; no exceptions are handled.

Explanation
===========
A try expression should be followed by some mechanism to handle any exceptions
thrown. Typically a catch expression follows the try and pattern matches
on any expected exceptions. For example:

import scala.util.control.NonFatal

try {} catch {
  case NonFatal(e) => ???
}

It is also possible to follow a try immediately by a finally - letting the
exception propagate - but still allowing for some clean up in finally:

try {} finally {
  // perform your cleanup here!
}

It is recommended to use the NonFatal extractor to catch all exceptions as it
correctly handles transfer functions like return.

1 warning found
